[package]
name = "github-rust-actions"
description = "GitHub actions for Rust written in Rust and compiled to WebAssembly"
version = "0.1.0"
repository = "https://github.com/FrancisRussell/github-rust-actions"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cargo_metadata = "0.15.2"
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.55"
parking_lot = "0.12.1"
regex = { version = "1.7.0", default_features = false, features = [ "std" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0.87"
shlex = "1.1.0"
thiserror = "1.0.23"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.33"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
lto = true
